### PR TITLE
RPC request for unknown Txs

### LINKED ISSUE #873: Transaction sync fixes
Transaction syncing fails when attempting to cache transactions. Re-enable caching and rewrite syncing algorithm to improve performance.

### PR DESCRIPTION
**Pull request by wkaluza**
Closes #873

### CODE REVIEW

File: libs/ledger/include/ledger/chain/mutable_transaction.hpp [hunk 1]
```diff
@@ -583,5 +584,7 @@ void Deserialize(T &serializer, Signatory &b)
   serializer >> b.first >> b.second;
 }
 
+using TxDigestSet = std::unordered_set<TransactionSummary::TxDigest>;
```
Comment (ejfitzgerald) [inline libs/ledger/include/ledger/chain/mutable_transaction.hpp:587]: 👍

File: libs/ledger/src/storage_unit/storage_unit_client.cpp [hunk 2]
```diff
@@ -453,6 +454,24 @@ bool StorageUnitClient::HasTransaction(ConstByteArray const &digest)
   return present;
 }
 
+void StorageUnitClient::IssueCallForMissingTxs(TxDigestSet const &tx_set)
+{
+  std::map<Address, std::unordered_set<ResourceID>> lanes_of_interest;
+  for (auto const &hash : tx_set)
+  {
+    ResourceID resource{hash};
+    lanes_of_interest[LookupAddress(resource)].insert(resource);
```
Comment (ejfitzgerald) [inline libs/ledger/src/storage_unit/storage_unit_client.cpp]: Minor: Move here a little more efficient

File: libs/ledger/src/storage_unit/transaction_finder_protocol.cpp [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+
+#include "ledger/storage_unit/transaction_finder_protocol.hpp"
+
+namespace fetch {
+namespace ledger {
+
+/**
+ * Create a transaction store sync protocol
+ *
+ * @param p The protocol id for this service
```
Comment (ejfitzgerald) [inline libs/ledger/src/storage_unit/transaction_finder_protocol.cpp]: Looks like this documentation doesn't belong here.

On another note, I think that new files that we create we should probably try and document them

File: libs/ledger/src/storage_unit/transaction_store_sync_service.cpp [hunk 4]
```diff
@@ -302,8 +304,25 @@ TransactionStoreSyncService::State TransactionStoreSyncService::OnQueryObjects()
     return State::QUERY_OBJECTS;
   }
 
+  std::vector<ResourceID> rids;
+  ResourceID              rid;
+  while (tx_finder_protocol_->Pop(rid))
```
Comment (ejfitzgerald) [inline libs/ledger/src/storage_unit/transaction_store_sync_service.cpp]: It would be my preference to add a hard limit to the number of transactions that can be requested in a single iteration. In addition I would used this number to preallocate the `rids` vector

File: libs/ledger/tests/chain/fake_storage_unit.cpp [hunk 5]
```diff
@@ -129,7 +132,8 @@ FakeStorageUnit::Hash FakeStorageUnit::CurrentHash()
 
 FakeStorageUnit::Hash FakeStorageUnit::LastCommitHash()
 {
-  assert(state_history_stack_.size() != 0);
+  assert(!state_history_stack_.empty());
```
Comment (ejfitzgerald) [inline libs/ledger/tests/chain/fake_storage_unit.cpp:135]: 👍

**Review by ejfitzgerald — CHANGES_REQUESTED** [review]

**Review by ejfitzgerald — APPROVED** [review]
