### PR TITLE
Fix for bahviour of default value in State<...> constructor

### LINKED ISSUE #1073: Possible bug: state var assigned and not explicitly .set() usable but not globally persistent
From developer slack user. Surrounding editorial is:

>Here's another one (not sure if this is a bug):
>when the value of a state var is only assigned and not explicitly .set() it is locally useable, but not globally persistent (see test2() getting different value).
>At least docu does not state this. And I think this might lead to much lost money in contracts and would suggest assigned values should be persistent (globally)

Issue could be documentation related. 

[stateSet.txt](https://github.com/uvue-git/fetch-ledger/files/3231475/stateSet.txt)

### PR DESCRIPTION
**Pull request by pbukva**
Closes: #1073

### CODE REVIEW

File: libs/vm/include/vm/state.hpp [hunk 1]
```diff
@@ -149,10 +149,25 @@ class State : public IState
...
   }
 
-  ~State() override = default;
+  ~State() override
+  {
+    try
+    {
+      FlushIO();
+    }
+    catch (...)
```
Comment (ejfitzgerald) [inline libs/vm/include/vm/state.hpp:171]: Think that it is worth catching the `std::exception` here and then added the message to the runtime error.

**Comment by ejfitzgerald** [comment]
FYI: @fetchai/docs This new `State` behaviour will need to be updated in the documentation

File: libs/vm/include/vm/state.hpp (hunk 1 above)
Comment (pbukva) [reply libs/vm/include/vm/state.hpp:171]: Can do, I was originally thinking about it, but over the time I grew dislike of multiple `catch` blocks in name of lazyness and concise code (we will have to have `catch(...)` block anyway as ultimate fallback since we are in destructor).

**Review by ejfitzgerald — APPROVED** [review]

**Comment by ejfitzgerald** [comment]
@pbukva I am going to land this because i want to cut the release this morning
