### PR TITLE
Bugfix/remove exceptions fixedpoint

### LINKED ISSUE #843: Add proper support for NaN/Infinity/etc in FixedPoint<> class
Add proper support for NaN/Infinity/etc in FixedPoint<> class

### PR DESCRIPTION
**Pull request by markos**
Complete NaN/Infinity support for FixedPoint, does not throw an exception anymore, instead a state variable is used which can be cleared and checked for NaN/Infinity/Overflow/Underflow/Division by Zero errors.

Closes: #843

### CODE REVIEW

File: libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp [hunk 1]
```diff
@@ -215,29 +215,53 @@ class FixedPoint : public BaseFixedpointType
...
+    STATE_OK               = 0,
+    STATE_NAN              = 1 << 0,
+    STATE_DIVISION_BY_ZERO = 1 << 1,
+    STATE_UNDERFLOW        = 1 << 2,
+    STATE_OVERFLOW         = 1 << 3,
+    STATE_INFINITY         = 1 << 4,
+  };
+  static uint32_t fp_state;
+
+  static constexpr void stateClear();
```
Comment (baykaner) [inline libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp]: style:
StateClear
IsState
IsStateNaN
etc.

File: libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp [hunk 2]
```diff
@@ -729,7 +753,10 @@ template <typename T>
 constexpr FixedPoint<I, F>::FixedPoint(T n, meta::IfIsFloat<T> *)
   : data_(static_cast<typename FixedPoint<I, F>::Type>(n * ONE_MASK))
 {
-  assert(CheckNoOverflow(n * ONE_MASK));
+  if (CheckNoOverflow(n * ONE_MASK))
+  {
+    fp_state |= STATE_OVERFLOW;
+  }
   //    assert(CheckNoRounding<T>());
```
Comment (baykaner) [inline libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp]: is this a leftover comment?

File: libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp [hunk 3]
```diff
@@ -1169,9 +1234,48 @@ constexpr FixedPoint<I, F> &FixedPoint<I, F>::operator--()
...
+    }
+    else
+    {
+      fp_state |= STATE_INFINITY;
+      return POSITIVE_INFINITY;
+    }
+  }
+  else if (isNegInfinity(*this))
+  {
+    // Adding +∞ to -∞ gives NaN, +∞ otherwise
```
Comment (baykaner) [inline libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp]: incorrect comment
(negative infinity otherwise)

File: libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp [hunk 4]
```diff
@@ -1182,9 +1286,48 @@ constexpr FixedPoint<I, F> FixedPoint<I, F>::operator+(FixedPoint<I, F> const &n
...
+    }
+    else
+    {
+      fp_state |= STATE_INFINITY;
+      return POSITIVE_INFINITY;
+    }
+  }
+  else if (isNegInfinity(*this))
+  {
+    // Subtracting -∞ from -∞ gives NaN, +∞ otherwise
```
Comment (baykaner) [inline libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp]: same for this comment

**Review by baykaner — CHANGES_REQUESTED** [review]

File: libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp (hunk 1 above)
Comment (markos) [reply libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp]: ack

File: libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp (hunk 3 above)
Comment (markos) [reply libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp]: fixed.

File: libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp (hunk 4 above)
Comment (markos) [reply libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp]: fixed

File: libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp (hunk 2 above)
Comment (markos) [reply libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp]: removed comment for now, will investigate the need for rounding separately

**Review by baykaner — APPROVED** [review]
