### PR TITLE
Bug/772 stdset of byte arrays

### LINKED ISSUE #772: ConstByteArray doesn't work with std::set for some reason

### PR DESCRIPTION
**Pull request by bipll**
All tests (byte array and smart contracts) seem to work just nice with std::set. Whatever behaviour led to #772 was probably caused by something else.

Closes #772

### CODE REVIEW

File: libs/ledger/src/chaincode/smart_contract.cpp [hunk 1]
```diff
@@ -64,13 +64,20 @@ ConstByteArray GenerateDigest(std::string const &source)
  */
 void ValidateAddressesInParams(Transaction const &tx, vm::ParameterPack const &params)
 {
-  // TODO(issue 772): This doesn't work with a set
-  std::unordered_set<ConstByteArray> valid_addresses;
+  std::set<ConstByteArray> valid_addresses;
 
+  std::cerr << "Validating " << tx.signatures().size() << " addresses\n";
```
Comment (n-hutton) [inline libs/ledger/src/chaincode/smart_contract.cpp]: Don't think we want to have these cerr here - use FETCH_LOG_DEBUG if that's desired

**Review by n-hutton — CHANGES_REQUESTED** [review]

**Review by n-hutton — APPROVED** [review]
lgtm
